### ISSUE TITLE
Crashing reported on 64-bit devices

### ISSUE THREAD

**Issue by rmtheis** [rmtheis/tess-two#197]
Needs investigation as to which architectures are affected, and when the issue was introduced.

**Comment by rmtheis** [comment]
### 6.2.0

armv7: No crash
x86_64: Crash


### 6.1.1			

armv7: No crash
x86_64: Crash

**Comment by rmtheis** [comment]
A workaround for this issue was committed in https://github.com/rmtheis/tess-two/commit/688d487b11c2e8d17816fd91ba7de5a3c1cfd041. 64-bit devices will fall back to run the 32-bit ABIs instead of the 64-bit versions, avoiding the crashing.

**Comment by wangyangke** [comment]
This bug is solved?

**Comment by wangyangke** [comment]
Don't build 64-bit ABIs by default，i edit your app module's build.gradle file to add tess-two as an external dependency:

dependencies {
    compile 'com.rmtheis:tess-two:8.0.0'
}, but still  crash

**Comment by rmtheis** [comment]
@wangyangke Try File->Invalidate Caches and Restart. Otherwise please file an issue with more info.

**Comment by jenia** [comment]
@rmtheis This does not avoid the error for me unfortunately.

I'm still getting a crash which says: 

    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/org.opencv.engine-1/lib/arm64/libopencv_java3.so" is 64-bit instead of 32-bit

Do you know how can I fix this?

Thanks kindly.

**Comment by anonym24** [comment]
@jenia  

try

```
ndk {
    abiFilters 'armeabi-v7a', "x86"
}
```

**Comment by SahSantoshh** [comment]
@jenia 
did you find the fix, I got this. Why these kind of errors occurs.

> A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe422613f in tid 26569 (AsyncTask #3)

**Comment by rmtheis** [comment]
@SahSantoshh Please open a new issue for the problem you're seeing with steps to reproduce the problem on an emulator. We'd like to be able to look into your issue and fix it.

**Comment by SahSantoshh** [comment]
Hi @rmtheis Thanks for your concern. But I fixed the issue by adding two line of code in manifest.xml file.

```
android:largeHeap="true"
android:hardwareAccelerated="false"
```

**Comment by amatsegor** [comment]
Soooo, that is still an only solution?
And if I'm using not only tesseract native library, but some other ones, I still should manually put 32-bit .so files into my project ?
Do you consider this issue as closed ?
